### ISSUE TITLE
How would one use HAC-Net to predict affinity values using an .sdf and/or .pdb file

### ISSUE THREAD

**Issue by Tonylac77** [gregory-kyro/HAC-Net#1]
Hi, I was wondering if you could explain how I could use HAC-Net to predict the binding affinity of a set of compounds (docking poses) stored as an .sdf file and using a protein .pdb file?

Many thanks

**Comment by gregory-kyro** [comment]
Dear Antoine:

In order for use in HAC-Net, you need to provide the model your data in .hdf format. This can be achieved with the code provided in the repository under **process_data**: 

https://github.com/gregory-kyro/HAC-Net/tree/main/process_data

There, you can also find a brief procedure on the necessary steps to follow in order to properly assemble the data. Additionally, I am attaching a file that should outline the procedure step-by-step for you:

[Data_preprocessing_for_Antoine.pdf](https://github.com/gregory-kyro/HAC-Net/files/10383268/Data_preprocessing_for_Antoine.pdf)


You can then simply use the HAC-Net tutorial notebook that is provided here: 

https://drive.google.com/drive/folders/1yB2voUxwzhrQRh0JXnOD3BzY8ZQrbgUK?usp=sharing

where all you will need to do is use the _predict_ function on the .hdf file that you create. If you want to return the predictions for each complex, I would recommend using the notebook that contains the source code and adding a print statement to return the predicted values.

I hope this helps. Please let me know if you have any questions.

Best,
Gregory

**Comment by gregory-kyro** [comment]
Additionally, we are working to provide more features for users to make this much simpler in the future, such as inputting a .pdb file directly without need of preprocessing the data beforehand. You can expect this option to be available in the near future.

**Comment by Tonylac77** [comment]
Dear Gregory,

Thanks for your quick answer, I think I will have to wait until you simplify this process as you mentioned, as I am planning to use this within a python script, and the need to generate charges with the server or by building the required library will clash with what I have in mind regarding user friendliness. I will watch this space carefully though. Thanks a lot!

**Comment by Tonylac77** [comment]
Hi, I just saw you released an update that can handle molecule files. Could you provide instructions as to how to do that? I haven't seen it in the notebook examples.
Many thanks for your work!

**Comment by gregory-kyro** [comment]
Dear Antoine:

We have been working on the backend software for a Python package module that takes in a protein coordinate file (pdb format) and a ligand coordinate file (mol2 format), and outputs a prediction of the binding affinity between them in about 1 second. We are also going to provide a corresponding Google Colab tutorial notebook. This will be pushed out and made available in the next 2-3 days. Thank you for your patience! Please don't hesitate to reach out with any further questions. I will let you know as soon as both the source code and notebook are made available.

Best,
Gregory

**Comment by gregory-kyro** [comment]
Hi Antoine,

We have now released a new version of the HACNet Python package that allows you to input protein and ligand structural files and receive a prediction of the binding affinity in a few seconds without the need of any external programs. There is now a demo video in the README of this repository, and we also link a tutorial notebook. Please let me know if you have any questions or need any additional help.

Best,
Gregory
